spring:
  application:
    name: fegin-consumer#  main:#    allow-bean-definition-overriding: true

server:
  port: 40000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:20000/eureka/
      