spring:
  application:
    name: config-server-eureka  cloud:    config:      server:        git:
          uri: https://github.com/lk182455145/spring-cloud-config.git
          #强制拉取资源文件
          force-pull: true
          #对应根目录下的某个目录
#          search-paths:#          username: 
#          password:             
        
server:
  port: 60001

eureka:  client:    service-url:      defaultZone: http://localhost:20000/eureka/