spring:
  application:
    name: feign-client#  main:#    allow-bean-definition-overriding: true

server:
  port: 40001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:20000/eureka/
      